Feat/services
chescobarf/MonitorAPP pull request #3
Opened 2021-07-06 21:07 UTC by chescobarf

## End of functional service.

### Latest updates:

#### Event creation:
- Variable time interval
- Total VS Notify data comparison
- Sending Email

2021-07-08 16:26 UTC, VioletaLibertad requested changes
Great job Chris! 🎉  Just some comments regarding unused code, formatting and some pesky `console.logs` here and there 🤓

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/events/updateMonitors.ts
> +// import { JsonToNumber } from '../utils'
Delete this line

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/events/updateMonitors.ts
> +  const workspace = ctx.vtex.workspace
Could be possible to use destructuring here? Ex:

const { account, workspace } = ctx.vtex

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/index.ts
> +// const TIMEOUT_MS = 10000
Delete this ;)

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/index.ts
> +// }
Please delete this unused lines 👌

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/index.ts
> +//TO HERE
? xD

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/emails.ts
> +const emailsEstado = "emails".concat(estado)
If is not that much trouble, it would be great to have this names in english 👌

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/emails.ts
> +  `http://${ctx.vtex.account}.myvtex.com/api/dataentities/OM/documents/${idEntity}/?_fields=${emailsEstado}`
indentation please :D

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/emailsPatch.ts
> +console.log(emailsEstado);
Delete this! :D

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/notificationPatch.ts
>    const  number = ctx.vtex.route.params.number
Could this be done with destructuring too? :o

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/notificationPatch.ts
> +console.log(data);
Delete this!

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/setUpdateTime.ts
> +  `http://${ctx.vtex.account}.myvtex.com/api/dataentities/OM/documents/${idEntity}`,{"updatetime":time}
Indentantion please <3

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/setUpdateTime.ts
> +console.log(data);
Delete me :D

2021-07-08 16:26 UTC, VioletaLibertad commented on Service-Component/node/middlewares/totalOrders.ts
>  const  status = ctx.vtex.route.params.status
Double space between `const` and `status` 🤓

2021-07-30 13:56 UTC, chescobarf commented on Service-Component/node/index.ts
> +//TO HERE
Nani? 👁

2021-07-30 13:59 UTC, chescobarf commented on Service-Component/node/middlewares/emailsPatch.ts
> +console.log(emailsEstado);
Why?

2021-07-30 14:01 UTC, chescobarf commented on Service-Component/node/middlewares/emailsPatch.ts
> +console.log(emailsEstado);
I delete the console.log, but the code above is functional

2021-07-30 14:02 UTC, VioletaLibertad commented on Service-Component/node/middlewares/emailsPatch.ts
> +console.log(emailsEstado);
I think I was referring only to the console.log, sorry the confusion 😅

2021-07-30 14:29 UTC, VioletaLibertad approved these changes
![](https://media.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif)

2021-08-03 17:09 UTC, merged